### PR TITLE
Added more robust argument parsing...

### PR DESCRIPTION
**Pull request by Emily-TTG**
Added skeleton for search path support

Need trunk Piccolo backend support for search paths - probably some kind of engine state which gets read in `piccolo_createPackage` or `piccolo_loadPackage`?

### CODE REVIEW

**Comment by Emily-TTG** [comment]
Switched to draft since this is still technically incomplete

**Comment by Nikos1001** [comment]
This looks pretty good. The only things I'd change is that the code uses snake_case in some places, and it doesn't look like it throws an error if the user does something like `piccolo test1.pic test2.pic`. Other than that it looks like a pretty nice extendable system. Thanks a ton!

**Comment by Emily-TTG** [comment]
I've fixed the merge issues- I think we can probably leave package support for later and just merge the new parsing for now

**Comment by Nikos1001** [comment]
Looks good! Thanks a lot :)

**Pull request merged**
